# Generated by Django 3.0.8 on 2020-07-17 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_car_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=10)),
                ('car', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.Car')),
            ],
        ),
    ]
